# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkClock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def __init__(self):
        self.Timer = QtCore.QTimer()
        self.Timer.setInterval(1000)
        self.Timer.timeout.connect(self.DecTime)

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Start_btn.setGeometry(QtCore.QRect(290, 120, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Start_btn.setFont(font)
        self.Start_btn.setObjectName("Start_btn")
        self.Stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_btn.setGeometry(QtCore.QRect(10, 120, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Stop_btn.setFont(font)
        self.Stop_btn.setAcceptDrops(False)
        self.Stop_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Stop_btn.setAutoFillBackground(False)
        self.Stop_btn.setObjectName("Stop_btn")
        self.TimerSettings_input = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimerSettings_input.setGeometry(QtCore.QRect(140, 30, 110, 30))
#        self.TimerSettings_input.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.TimerSettings_input.setObjectName("TimerSettings_input")
        self.Config_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Config_lbl.setGeometry(QtCore.QRect(10, 10, 340, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.Config_lbl.setFont(font)
        self.Config_lbl.setObjectName("Config_lbl")
        self.Cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel_btn.setGeometry(QtCore.QRect(140, 120, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Cancel_btn.setFont(font)
        self.Cancel_btn.setAcceptDrops(False)
        self.Cancel_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Cancel_btn.setAutoFillBackground(False)
        self.Cancel_btn.setObjectName("Cancel_btn")
        self.OutputTime_lbl = QtWidgets.QLabel(self.centralwidget)
        self.OutputTime_lbl.setGeometry(QtCore.QRect(140, 80, 110, 30))
        self.OutputTime_lbl.setText("")
        self.OutputTime_lbl.setObjectName("OutputTime_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connected handler with btns
        self.Start_btn.clicked.connect(lambda: self.ButtonClicked(self.Start_btn.objectName()))
        self.Stop_btn.clicked.connect(lambda: self.ButtonClicked(self.Stop_btn.objectName()))
        self.Cancel_btn.clicked.connect(lambda: self.ButtonClicked(self.Cancel_btn.objectName()))

    def ButtonClicked(self, btn_name):
        if btn_name == "Start_btn":
            text_time = self.TimerSettings_input.textFromDateTime(self.TimerSettings_input.dateTime())
            print(text_time)
            self.OutputTime_lbl.setText(text_time)
            self.Timer.start(1000)
        else:
            print(btn_name)

    def DecTime(self):
        print("DecTime Is run!")
        print(self.OutputTime_lbl.text())
        if self.OutputTime_lbl.text() != "00:00:00":
            _time = self.TimerSettings_input.dateTimeFromText(self.OutputTime_lbl.text()).addSecs(-1)
            text_time = self.TimerSettings_input.textFromDateTime(_time)
            print(text_time)
            self.OutputTime_lbl.setText(text_time)

        else:
            self.Timer.stop()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WorkClock"))
        self.Start_btn.setText(_translate("MainWindow", "Start"))
        self.Stop_btn.setText(_translate("MainWindow", "Stop"))
        self.TimerSettings_input.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.Config_lbl.setText(_translate("MainWindow", "Stopwatch"))
        self.Cancel_btn.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
